---
repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - args:
          - --maxkb=1000000
        id: check-added-large-files
      - id: detect-private-key
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: sort-simple-yaml
      - id: check-yaml
      - id: check-json
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
  - hooks:
      - id: optimize-png
      - id: optimize-jpg
      # FIXME: Keeps endlessly optimising
      # - id: optimize-webp
      #   args: [--threshold=2]
      - id: optimize-svg
    repo: https://github.com/boidolr/pre-commit-images
    rev: v1.8.2
