---
repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - args:
          - --maxkb=3000
        id: check-added-large-files
      - id: detect-private-key
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: sort-simple-yaml
      - id: check-yaml
      - id: check-json
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
  - hooks:
      - id: optimize-png
      - id: optimize-jpg
    repo: https://github.com/boidolr/pre-commit-images
    rev: v1.0.6
  - hooks:
      - entry: linkchecker-markdown
        id: linkchecker-markdown
        language: system
        name: linkchecker-markdown
        types:
          - python
    repo: local
  - hooks:
      - id: commitizen
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.32.2
