---
baseURL: "https://shivan.xyz/"
languageCode: "en-us"
title: "Shivan Sivakumaran"
theme: "optom-code"
defaultContentLanguage: en

enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: false

minify:
  minifyOutput: true

params:
  author:
    name: Shivan Sivakumaran
    email: me@shivan.xyz
