baseURL: "https://shivan.xyz/"
languageCode: "en-us"
title: "Shivan Sivakumaran"
theme: "PaperMod"
paginate: 7
defaultContentLanguage: en

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: G-N8YH79QGZ2

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Shivan Sivakumaran
  description: "Shivan Sivakumaran Blog"
  keywords: [Blog, Programming, Optometry, Life]
  author: Shivan Sivakumaran
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: true
  comments: true
  disableScrollToTop: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
  disableHLJS: true # to disable highlight.js
  # disableFingerprinting: true
  favicon: favicon.png
  favicon16x16: favicon.png
  favicon32x32: favicon.png
  apple_touch_icon: favicon.png
  safari_pinned_tab: favicon.png

  label:
    text: "Shivan Sivakumaran"
    icon: favicon.ico
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Shivan Sivakumaran
    subtitle: Optometrist -> Technology
    imageUrl: avatar.png
    imageWidth: 120
    imageHeight: 120
    imageTitle: Me!
    buttons:
      - name: About
        url: about
      - name: Posts
        url: posts
      - name: Categories
        url: categories

  # home-info mode
  homeInfoParams:
    Title: "Welcome \U0001F44B"
    Content: >
      A blog. \

      [Who am I?](https://shivan.xyz/about)

  socialIcons:
    - name: youtube
      url: "https://youtube.com/c/shivansivakumaran"
    - name: github
      url: "https://github.com/shivan-s"
    - name: twitter
      url: "https://twitter.com/shivsivakumaran"
    - name: linkedin
      url: "https://linkedin.com/in/shivansivakumaran"
    - name: instagram
      url: "https://instagram.com/shivan_s"

  analytics:
    google:
      SiteVerificationTag: "G-N8YH79QGZ2"

  disqusShortname: shivan-xyz

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page
    responsiveImages: false
    linkFullImages: false

  editPost:
    URL: "https://github.com/shivan-s/shivan.xyz/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: about
      name: about
      url: /about/
      weight: 1
    - identifier: projects
      name: projects
      url: /projects/
      weight: 2
    - identifier: categories
      name: categories
      url: /categories/
      weight: 3
    - identifier: archives
      name: archives
      url: /archives/
      weight: 4
