baseURL: "http://shivan.xyz/"
languageCode: "en-us"
title: "Shivan Sivakumaran"
theme: mini
defaultContentLanguage: en

hasCJKLanguage: true

paginate: 10

# googleAnalytics: <enter this>
# disqusShortname: <what is it again?>

markup:
  highlight:
    guessSyntax: false
    style: emacs
  tableOfContents:
    endlevel: 10
    ordered: false
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true

googleAnalytics: G-FDWQMYMSBT
disqusShortname: shivan-xyz

social:
  # youtube: 'https://youtube.com/c/ShivanSivakumaran'
  twitter: "https://twitter.com/ShivSivakumaran"
  github: "https://github.com/ShivanS93"

taxonomies:
  tag: tags
  category: categories

params:
  author: Shivan Sivakumaran
  bio: Optometrist
  description: Welcome to my thoughts.
  enableRSS: false
  enableComments: true
  enableGoogleAnalytics: true
  showToc: true
  showPowerBy: false
  math: false
  hiddenPostSummaryInHomePage: false
  copyright: "Shivan Sivakumaran"
  customCSS:
    - css/custom.css
