name: Check Markdown Links

on:
  - push
  - pull_request

jobs:
  check-markdown-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Markdown Linter
        uses: gaurav-nelson/github-action-markdown-link-check@v1
